/*
 * MainForm.java
 *
 * Created on 02 February 2009, 11:43
 */

package uk.co.exahertz.friendlysociety.gui;

/**
 *
 * @author  kal8
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileImport = new javax.swing.JMenuItem();
        fileExport = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();
        customerMenu = new javax.swing.JMenu();
        customerAdd = new javax.swing.JMenuItem();
        CustomerEdit = new javax.swing.JMenuItem();
        customerDelete = new javax.swing.JMenuItem();
        staffMenu = new javax.swing.JMenu();
        staffAdd = new javax.swing.JMenuItem();
        staffEdit = new javax.swing.JMenuItem();
        staffDelete = new javax.swing.JMenuItem();
        mortgageMenu = new javax.swing.JMenu();
        mortgageAdd = new javax.swing.JMenuItem();
        mortgageEdit = new javax.swing.JMenuItem();
        mortgageDelete = new javax.swing.JMenuItem();
        mortgagePaymentDetails = new javax.swing.JMenuItem();
        pendingMenu = new javax.swing.JMenu();
        pendingView = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpAbout = new javax.swing.JMenuItem();

        menu1.setLabel("Menu");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menuBar1.add(menu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        fileImport.setText("Import");
        fileImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileImportActionPerformed(evt);
            }
        });
        fileMenu.add(fileImport);

        fileExport.setText("Export");
        fileMenu.add(fileExport);

        fileExit.setText("Exit");
        fileMenu.add(fileExit);

        jMenuBar1.add(fileMenu);

        customerMenu.setText("Customer");

        customerAdd.setText("Add");
        customerMenu.add(customerAdd);

        CustomerEdit.setText("Edit");
        customerMenu.add(CustomerEdit);

        customerDelete.setText("Delete");
        customerMenu.add(customerDelete);

        jMenuBar1.add(customerMenu);

        staffMenu.setText("Staff");

        staffAdd.setText("Add");
        staffMenu.add(staffAdd);

        staffEdit.setText("Edit");
        staffMenu.add(staffEdit);

        staffDelete.setText("Delete");
        staffMenu.add(staffDelete);

        jMenuBar1.add(staffMenu);

        mortgageMenu.setText("Mortgage");

        mortgageAdd.setText("Add");
        mortgageMenu.add(mortgageAdd);

        mortgageEdit.setText("Edit");
        mortgageMenu.add(mortgageEdit);

        mortgageDelete.setText("Delete");
        mortgageMenu.add(mortgageDelete);

        mortgagePaymentDetails.setText("View Payment Details");
        mortgageMenu.add(mortgagePaymentDetails);

        jMenuBar1.add(mortgageMenu);

        pendingMenu.setText("Pending Applications");

        pendingView.setText("View Pending Apps.");
        pendingMenu.add(pendingView);

        jMenuBar1.add(pendingMenu);

        helpMenu.setText("Help");

        helpAbout.setText("About");
        helpMenu.add(helpAbout);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_menu1ActionPerformed

private void fileImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileImportActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_fileImportActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CustomerEdit;
    private javax.swing.JMenuItem customerAdd;
    private javax.swing.JMenuItem customerDelete;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileExport;
    private javax.swing.JMenuItem fileImport;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem helpAbout;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu1;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem mortgageAdd;
    private javax.swing.JMenuItem mortgageDelete;
    private javax.swing.JMenuItem mortgageEdit;
    private javax.swing.JMenu mortgageMenu;
    private javax.swing.JMenuItem mortgagePaymentDetails;
    private javax.swing.JMenu pendingMenu;
    private javax.swing.JMenuItem pendingView;
    private javax.swing.JMenuItem staffAdd;
    private javax.swing.JMenuItem staffDelete;
    private javax.swing.JMenuItem staffEdit;
    private javax.swing.JMenu staffMenu;
    // End of variables declaration//GEN-END:variables

}
